#title: AVERtek # your name photo (or website title) here
logo1: "/images/avenidaPDlogo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <b><h3>LIVE YOUR DREAM RETIREMENT</h3></b> 
  <b>POWERFUL BREADCRUMB MARKETING WITH STORYTELLING LINKS</b> <br>
    3D IMAGE allows Viewer to rotate, spin & zoom to scale the Fairytale Story
  <br><br> 
  <b>SHOW IMAGES/EVENTS THAT ROMANCE COMMUNITY LIVING</b> <br>
   Augmented Reality (AR) transports your story into the Prospect's memory!
  <br><br>
  <a href="https://avertek.net/xr-now-apartments"><b><u>LINK EXCITING STORIES/CONTENT</u></b>- Help Prospects visualize a new lifestyle</a> 
  <br><br>
  <a href="https://youtu.be/5YSBRmMTybU"><b><u>SHARE TESTIMONIALS</u></b>- Show viewers fun/friendly residents</a>
  <br><br>
  <a href="https://avertek.net/contact-us"><b><u>EXPERIENCE "LIVING LIFE TODAY"</u></b>- Take a VIP tour, Get a special gift</a> 
  <br><br>

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
